"""create initial tables

Revision ID: 0f61e2931c34
Revises: 
Create Date: 2025-07-16 10:33:28.441848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f61e2931c34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('job_name', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_group', sa.String(), nullable=True),
    sa.Column('queue', sa.String(), nullable=True),
    sa.Column('job_status', sa.String(), nullable=True),
    sa.Column('nodes', sa.Integer(), nullable=True),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('memory', sa.String(), nullable=True),
    sa.Column('run_time_seconds', sa.BigInteger(), nullable=True),
    sa.Column('queue_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('elapse_limit_seconds', sa.BigInteger(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_jobs_queue'), 'jobs', ['queue'], unique=False)
    op.create_index(op.f('ix_jobs_resource_type'), 'jobs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_jobs_user_group'), 'jobs', ['user_group'], unique=False)
    op.create_index(op.f('ix_jobs_user_name'), 'jobs', ['user_name'], unique=False)

    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_name'), 'wallets', ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.create_table('quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cpu_core_hours_limit', sa.Float(), nullable=True),
    sa.Column('gpu_core_hours_limit', sa.Float(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotas_id'), 'quotas', ['id'], unique=False)
    op.create_index(op.f('ix_quotas_user_id'), 'quotas', ['user_id'], unique=False)

    op.create_table('group_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_group', sa.String(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_mappings_id'), 'group_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_group_mappings_source_group'), 'group_mappings', ['source_group'], unique=True)
    op.create_index(op.f('ix_group_mappings_target_user_id'), 'group_mappings', ['target_user_id'], unique=False)

    op.create_table('processed_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_files_filename'), 'processed_files', ['filename'], unique=True)
    op.create_index(op.f('ix_processed_files_id'), 'processed_files', ['id'], unique=False)

    op.create_table('group_to_group_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_group', sa.String(), nullable=True),
    sa.Column('target_group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_to_group_mappings_id'), 'group_to_group_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_group_to_group_mappings_source_group'), 'group_to_group_mappings', ['source_group'], unique=True)
    op.create_index(op.f('ix_group_to_group_mappings_target_group'), 'group_to_group_mappings', ['target_group'], unique=False)

    op.create_table('group_to_wallet_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_group', sa.String(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_to_wallet_mappings_id'), 'group_to_wallet_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_group_to_wallet_mappings_source_group'), 'group_to_wallet_mappings', ['source_group'], unique=True)

    op.create_table('user_to_wallet_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_to_wallet_mappings_id'), 'user_to_wallet_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_user_to_wallet_mappings_user_id'), 'user_to_wallet_mappings', ['user_id'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_to_wallet_mappings_user_id'), table_name='user_to_wallet_mappings')
    op.drop_index(op.f('ix_user_to_wallet_mappings_id'), table_name='user_to_wallet_mappings')
    op.drop_table('user_to_wallet_mappings')
    op.drop_index(op.f('ix_group_to_wallet_mappings_source_group'), table_name='group_to_wallet_mappings')
    op.drop_index(op.f('ix_group_to_wallet_mappings_id'), table_name='group_to_wallet_mappings')
    op.drop_table('group_to_wallet_mappings')
    op.drop_index(op.f('ix_group_to_group_mappings_target_group'), table_name='group_to_group_mappings')
    op.drop_index(op.f('ix_group_to_group_mappings_source_group'), table_name='group_to_group_mappings')
    op.drop_index(op.f('ix_group_to_group_mappings_id'), table_name='group_to_group_mappings')
    op.drop_table('group_to_group_mappings')
    op.drop_index(op.f('ix_processed_files_id'), table_name='processed_files')
    op.drop_index(op.f('ix_processed_files_filename'), table_name='processed_files')
    op.drop_table('processed_files')
    op.drop_index(op.f('ix_group_mappings_target_user_id'), table_name='group_mappings')
    op.drop_index(op.f('ix_group_mappings_source_group'), table_name='group_mappings')
    op.drop_index(op.f('ix_group_mappings_id'), table_name='group_mappings')
    op.drop_table('group_mappings')
    op.drop_index(op.f('ix_quotas_user_id'), table_name='quotas')
    op.drop_index(op.f('ix_quotas_id'), table_name='quotas')
    op.drop_table('quotas')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_wallets_name'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_jobs_user_name'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_user_group'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_resource_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_queue'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
