"""remove_run_time_str_from_jobs

Revision ID: 2b924cdc9f45
Revises: 6a3e94a3daa1
Create Date: 2025-07-18 16:09:23.306531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b924cdc9f45'
down_revision: Union[str, None] = '6a3e94a3daa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'run_time_str')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('run_time_str', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
