"""Add group_to_group_mappings table

Revision ID: aeee40038c58
Revises: 0f61e2931c34
Create Date: 2025-07-16 11:52:12.686205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeee40038c58'
down_revision: Union[str, None] = '0f61e2931c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_to_group_mappings_target_group'), table_name='group_to_group_mappings')
    op.drop_index(op.f('ix_group_to_group_mappings_source_group'), table_name='group_to_group_mappings')
    op.drop_index(op.f('ix_group_to_group_mappings_id'), table_name='group_to_group_mappings')
    op.drop_table('group_to_group_mappings')
    # ### end Alembic commands ###
